### ISSUE TITLE
Is there a tracking issue on moby/moby for this?

### ISSUE THREAD

**Issue by friism** [rodrigozr/docker_shutdown#1]

**Comment by rodrigozr** [comment]
Hi @friism, no - we are working directly with Microsoft on this one. But I can certainly open an issue over there if that would help it being addressed.

**Comment by friism** [comment]
@rodrigozr it'd be great to have an issue on moby/moby in case other people hit the same problem.

**Comment by rodrigozr** [comment]
I found this old issue over there, which is exactly the same: https://github.com/moby/moby/issues/25982
